# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=20, verbose_name='Name')),
                ('desc', models.CharField(default='Extra info.', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'BizUnit',
                'verbose_name_plural': 'BizUnit',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=20, verbose_name='Name')),
                ('desc', models.CharField(default='Extra info.', max_length=40, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Cluster',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='NULL', max_length=10, verbose_name='Tag')),
                ('cpu', models.CharField(default='NULL', max_length=20, verbose_name='CPU')),
                ('memory', models.CharField(default='NULL', max_length=20, verbose_name='Memory')),
                ('disk_ssd', models.CharField(default='NULL', max_length=20, verbose_name='Disk SSD')),
                ('disk_sas', models.CharField(default='NULL', max_length=20, verbose_name='Disk SAS')),
                ('disk_sata', models.CharField(default='NULL', max_length=20, verbose_name='Disk SATA')),
                ('nic', models.CharField(default='Onboard', max_length=20, verbose_name='NIC Card')),
                ('psu', models.IntegerField(default=1, verbose_name='PSU')),
                ('raid_card', models.CharField(default='NULL', max_length=20, verbose_name='RAID Card')),
                ('desc', models.CharField(default='Extra info.', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Type',
            },
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NULL', max_length=20, verbose_name='Username')),
                ('fullname', models.CharField(default='NULL', max_length=20, verbose_name='Fullname')),
                ('department', models.CharField(default='NULL', max_length=40, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'EndUser',
                'verbose_name_plural': 'EndUser',
            },
        ),
        migrations.CreateModel(
            name='IDCInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='NULL', max_length=10, verbose_name='Tag')),
                ('name', models.CharField(default='NULL', max_length=20, verbose_name='Name')),
                ('location', models.CharField(default='Extra info.', max_length=100, verbose_name='Location')),
                ('desc', models.CharField(default='Extra info.', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='NULL', max_length=10, verbose_name='Tag')),
                ('cpu', models.IntegerField(default=1, verbose_name='CPU(Core)')),
                ('memory', models.IntegerField(default=1, verbose_name='Memory(GB)')),
                ('desc', models.CharField(default='Extra info.', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Instance Type',
                'verbose_name_plural': 'Instance Type',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='Hostname')),
                ('os_ip_wan1', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP_WAN1')),
                ('os_ip_wan2', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP_WAN2')),
                ('os_ip_lan_mgmt', models.GenericIPAddressField(verbose_name='IP_LAN_MGMT')),
                ('os_ip_lan_stor', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP_LAN_STOR')),
                ('os_ip_lan_biz', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP_LAN_BIZ')),
                ('os_user_root', models.CharField(default='root', max_length=20, verbose_name='Admin')),
                ('os_pass_root', models.CharField(default='NULL', max_length=40, verbose_name='Password of Admin')),
                ('os_user_guest', models.CharField(default='root1', max_length=20, verbose_name='Guest')),
                ('os_pass_guest', models.CharField(default='NULL', max_length=40, verbose_name='Password of Guest')),
                ('app_desc', models.CharField(default='NOT_IN_USE', max_length=40, verbose_name='App Description')),
                ('is_monited', models.BooleanField(default=False, verbose_name='Is Monited?')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online?')),
                ('is_v_host', models.BooleanField(default=False, verbose_name='Is Virt Host?')),
                ('device_sn', models.CharField(default='NULL', max_length=40, verbose_name='SN')),
                ('device_ipmi_ip', models.GenericIPAddressField(default='192.168.0.120', verbose_name='IPMI IP')),
                ('device_ipmi_user', models.CharField(default='root', max_length=20, verbose_name='IPMI User')),
                ('device_ipmi_pass', models.CharField(default='calvin', max_length=40, verbose_name='IPMI Password')),
                ('device_raid_level', models.CharField(default='5', max_length=10, verbose_name='RAID')),
                ('desc', models.CharField(default='Extra info.', max_length=40, verbose_name='Description')),
                ('idc_rack', models.CharField(default='A01', max_length=10, verbose_name='IDC Rack No.')),
                ('idc_rack_h', models.IntegerField(default=0, verbose_name='IDC Rack Height')),
                ('asset_no', models.CharField(default='NULL', max_length=100, verbose_name='Asset No.')),
                ('dt_created', models.DateTimeField(verbose_name='When Created?')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='When Modified?')),
                ('biz_unit', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.BusinessUnit', verbose_name='BizUnit')),
                ('cluster', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.Cluster', verbose_name='Cluster')),
                ('idc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.IDCInfo', verbose_name='IDC')),
                ('model', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.DeviceType', verbose_name='Model')),
                ('operator', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.EndUser', verbose_name='EndUser')),
            ],
            options={
                'verbose_name': 'Machines',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='OSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='NULL', max_length=20, verbose_name='Tag')),
                ('desc', models.CharField(default='Extra info.', max_length=40, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'OS Type',
                'verbose_name_plural': 'OS Type',
            },
        ),
        migrations.CreateModel(
            name='RuntimeEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=20, verbose_name='Name')),
                ('desc', models.CharField(default='Extra info.', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'RunEnv',
                'verbose_name_plural': 'RunEnv',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=20, verbose_name='Name')),
                ('desc', models.CharField(default='Extra info.', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Vendors',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='Hostname')),
                ('os_ip_wan', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP_WAN')),
                ('os_ip_lan', models.GenericIPAddressField(verbose_name='IP_LAN')),
                ('os_user_root', models.CharField(default='root', max_length=20, verbose_name='Admin')),
                ('os_pass_root', models.CharField(default='NULL', max_length=40, verbose_name='Password of Admin')),
                ('os_user_guest', models.CharField(default='root1', max_length=20, verbose_name='Guest')),
                ('os_pass_guest', models.CharField(default='NULL', max_length=40, verbose_name='Password of Guest')),
                ('is_monited', models.BooleanField(default=False, verbose_name='Is Monited?')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online?')),
                ('app_desc', models.CharField(default='NOT_IN_USE', max_length=40, verbose_name='App Description')),
                ('mount_point', models.CharField(default='NULL', max_length=40, verbose_name='Mount Point')),
                ('desc', models.CharField(default='Extra info.', max_length=100, verbose_name='VM Description')),
                ('dt_created', models.DateTimeField(verbose_name='When Created?')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='When Modified?')),
                ('biz_unit', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.BusinessUnit', verbose_name='BizUnit')),
                ('instance_type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.InstanceType', verbose_name='Instance Type')),
                ('on_cluster', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.Cluster', verbose_name='On Cluster')),
                ('on_host', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.Machine', verbose_name='On Host')),
                ('on_idc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.IDCInfo', verbose_name='IDC')),
                ('operator', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.EndUser', verbose_name='EndUser')),
                ('os_type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.OSType', verbose_name='OS Type')),
                ('run_env', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.RuntimeEnvironment', verbose_name='RunEnv')),
            ],
            options={
                'verbose_name': 'VMs',
                'verbose_name_plural': 'VMs',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='os_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.OSType', verbose_name='OS Type'),
        ),
        migrations.AddField(
            model_name='machine',
            name='run_env',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.RuntimeEnvironment', verbose_name='RunEnv'),
        ),
        migrations.AddField(
            model_name='machine',
            name='vendor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='assets.Vendor', verbose_name='Vendor'),
        ),
    ]
